@apiUrl = http://localhost:3030/notes
#@apiUrl = https://wom-exempel-lahepela.azurewebsites.net/notes
@token = {{$dotenv TOKEN}}

###
GET {{apiUrl}}/650d60beba1ce6c5592c8fc9
Authorization: Bearer {{token}}

###
POST {{apiUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "My own note 2",
    "positionX": 1,
    "positionY": 1,
    "boardId": "650d60beba1ce6c5592c8fc9"
}

### 
PATCH {{apiUrl}}/650d65158cb1c4fca2e62948
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "My updated note"
}

###
DELETE {{apiUrl}}/650d65158cb1c4fca2e62948
Authorization: Bearer {{token}}

###