#@apiUrl = http://localhost:3030/notes
@apiUrl = https://lahepela-wom-project.azurewebsites.net/notes
@token = {{$dotenv TOKEN}}

###
GET {{apiUrl}}/650d60beba1ce6c5592c8fc9
Authorization: Bearer {{token}}

###
POST {{apiUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "My own note 1",
    "positionX": 40,
    "positionY": 40,
    "boardId": "65106552d22fabbe68d6830e"
}

### 
PATCH {{apiUrl}}/650d65158cb1c4fca2e62948
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "My updated note",
    "positionX": 40,
    "positionY": 40
}

###
DELETE {{apiUrl}}/650d65158cb1c4fca2e62948
Authorization: Bearer {{token}}

###